#!/bin/sh


status=$(acpi -b | awk '{printf $3}' | rev | cut -c2- | rev)
capacity=$(acpi -b | awk '{printf $4}' | rev | cut -c2- | rev)

case $BLOCK_BUTTON in
	6) $TERMINAL -e nvim "$0" ;;
	1) notify-send "Battery Status" "$(acpi -b | awk '{printf $5 " " $6}')";;
	3) notify-send "Battery Module" "";;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "

	capacity="$(cat "$battery/capacity" 2>&1)"
	if [ "$capacity" -gt 90 ]; then
		status=" "
	elif [ "$capacity" -gt 70 ]; then
		status=" "
	elif [ "$capacity" -gt 50 ]; then
		status=" "
	elif [ "$capacity" -gt 30 ]; then
		status=" "
	elif [ "$capacity" -gt 10 ]; then
		status=" "
	else
		status=" "
	fi

	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		Full) status="⚡" ;;
		Discharging)
			if [ "$capacity" -le 20 ]; then
				status="❗ $status"
				notify-send -u=low "WARNING BATTERY LOW" "Plug in soon"
			else
				status="🔋 $status"
			fi
			;;
		Charging) status="🔌 $status" ;;
		"Not charging") status="🛑 $status" ;;
		Unknown) status=" " ;;
		*) exit 1 ;;
	esac

#echo "$status $percent"
	


done && echo "$status $capacity"
